# SPDX-FileCopyrightText: 2022 Great Software Laboratory Pvt. Ltd
# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0


---
info:
  version: 1.0.0
  description: GNBSIM initial local configuration

configuration:
  singleInterface: false #default value
  execScenariosInParallel: false #run all scenarios in parallel
  execUesInParallel: false #run all profiles in parallel
  httpServer: # Serves APIs to create/control profiles on the go
    enable: false
    ipAddr: "POD_IP"
    port: 8080
  gnbs: # pool of gNodeBs
    gnb1:
      n2IpAddr: # gNB N2 interface IP address used to connect to AMF 
      n2Port: 9487 # gNB N2 Port used to connect to AMF
      n3IpAddr: 192.168.17.1 # gNB N3 interface IP address used to connect to UPF. when singleInterface mode is false
      #n3IpAddr: "POD_IP" # when gnb is deployed in singleInterface mode
      n3Port: 2152 # gNB N3 Port used to connect to UPF
      name: gnb1 # gNB name that uniquely identify a gNB within application
      globalRanId:
        plmnId:
          mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
        gNbId: 
          bitLength: 24
          gNBValue: 000102 # gNB identifier (3 bytes hex string, range: 000000~FFFFFF)
      supportedTaList:
        - tac: 000001 # Tracking Area Code (3 bytes hex string, range: 000000~FFFFFF)
          broadcastPlmnList:
            - plmnId:
                mcc: 208
                mnc: 93
              taiSliceSupportList:
                - sst: 1
                  sd: 16777215
  amfs:
    amf1:
      hostName: amf # Host name of AMF
      ipAddr: # AMF IP address
      port: 38412 # AMF port    
  ueProfiles: # profile information
    default: # uniquely identifies a profile within application
      startImsi: 208950000000031
      opc: "63bfa50ee6523365ff14c1f45f88737d"
      key: "0C0A34601D4F07677303652C0462535B"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "default"
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)

logger:
  logLevel: trace # how detailed the log will be, values: trace, debug, info, warn, error, fatal, panic
