# SPDX-FileCopyrightText: 2022 Great Software Laboratory Pvt. Ltd
# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0


---
info:
  version: 1.0.0
  description: GNBSIM initial local configuration

configuration:
  singleInterface: false #default value
  execScenariosInParallel: false #run all scenarios in parallel
  execUesInParallel: true #run UE scenarios in parallel
  httpServer: # Serves APIs to create/control profiles on the go
    enable: false
    ipAddr: "POD_IP"
    port: 8080
  gnbs: # pool of gNodeBs
    gnb1: # gNB name that uniquely identify a gNB within application
      n2IpAddr: # gNB N2 interface IP address used to connect to AMF 
      n2Port: 9487 # gNB N2 Port used to connect to AMF
      n3IpAddr: 192.168.17.1 # gNB N3 interface IP address used to connect to UPF. when singleInterface mode is false
      #n3IpAddr: "POD_IP" # when gnb is deployed in singleInterface mode
      n3Port: 2152 # gNB N3 Port used to connect to UPF
      name: gnb1 # gNB name that uniquely identify a gNB within application TODO make it equal to upper id    
      globalRanId:
        plmnId:
          mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: 95 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
        gNbId: 
          bitLength: 24
          gNBValue: 000102 # gNB identifier Equal to the leftmost bits of the NR Cell Identity IE contained in the NR CGI IE of each cell served by the gNB.
      nrCgiCellList:
        - plmnId:
            mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 95 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          nrCellId: 000102001 # gNB identifier (4.5 bytes hex string)
        - plmnId:
            mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 95 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          nrCellId: 000102002 # gNB identifier (4.5 bytes hex string)
      supportedTaList:
        - tac: 00a000 # Tracking Area Code (3 bytes hex string, range: 000000~FFFFFF)
          broadcastPlmnList:
            - plmnId:
                mcc: 208
                mnc: 95
              taiSliceSupportList:
                - sst: 1
                  sd: FFFFFF
                - sst: 1
                  sd: 000001
                - sst: 222
                  sd: 00007B
  amfs:
    amf1:
      hostName: amf # Host name of AMF
      ipAddr: # AMF IP address
      port: 38412 # AMF port
  ueProfiles: # profile information
    default: # uniquely identifies a profile within application
      startImsi: 208950000000031
      numUes: 1
      opc: "63bfa50ee6523365ff14c1f45f88737d"
      key: "0C0A34601D4F07677303652C0462535B"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "default"
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 95 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      provision:
        createSubscriber: no
        createRestUrl: http://192.168.70.136/nudr-dr/v1/subscription-data/SUBSCRIBER-SUPI/authentication-data/authentication-subscription
        deleteRestUrl: http://192.168.70.136/nudr-dr/v1/subscription-data/SUBSCRIBER-SUPI/authentication-data/authentication-subscription
        createJsonContent: |
          {
            "authenticationMethod":"5G_AKA",
            "encPermanentKey":"0C0A34601D4F07677303652C0462535B",
            "protectionParameterId":"0C0A34601D4F07677303652C0462535B",
            "sequenceNumber": {
                "sqn" : "000000000020", 
                "sqnScheme": "NON_TIME_BASED", 
                "lastIndexes": {
                    "ausf": 0 
                    }
                },
            "authenticationManagementField":"8000",
            "algorithmId":"milenage",
            "encOpcKey":"63bfa50ee6523365ff14c1f45f88737d",
            "encTopcKey":"63bfa50ee6523365ff14c1f45f88737d", 
            "vectorGenerationInHss": false, 
            "n5gcAuthMethod": "", 
            "rgAuthenticationInd": false, 
            "supi":"SUBSCRIBER-SUPI"
          }
logger:
  logLevel: trace # how detailed the log will be, values: trace, debug, info, warn, error, fatal, panic
