name: build-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, reopened, synchronize ]


jobs:

  build-x64:
    if: github.repository_owner == 'openairinterface'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7' 
    - name: Synchronize with merged branches in git sub-modules
      if: github.event_name == 'push'
      run: ./scripts/sync-sub-modules.py --synchronize --force
    - name: Synchronize with temptative branches in git sub-modules
      if: github.event_name == 'pull_request'
      run: ./scripts/sync-for-pull-request.sh
    - name: Create the docker image
      run: |
        cd third-party/gnbsim
        make docker-build
        # To see the size of the target image
        docker images
